version: '3.8'

services:
  backend:
    build: .
    image: cafe-backend-hf:latest
    container_name: cafe-backend-local
    restart: always
    ports:
      - "7860:7860"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://root:example_password@mongodb:27017/cafe_db?authSource=admin
      - PORT=7860
      - CORS_ALLOWED_ORIGINS=*
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: cafe-db-local
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example_password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
