server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 50
      min-spare: 5

spring:
  main:
    lazy-initialization: false

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: false

logging:
  level:
    root: INFO
    com.hostel.ordering: INFO
    org.springframework.data.mongodb: WARN

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}